# Generated by Django 5.2 on 2025-04-29 09:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('target_muscles', models.CharField(max_length=200)),
                ('equipment_needed', models.CharField(blank=True, max_length=200, null=True)),
                ('instruction_steps', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FitnessGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration_minutes', models.IntegerField(default=45)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.IntegerField(default=3)),
                ('reps', models.CharField(default='10-12', max_length=50)),
                ('rest_between_sets_seconds', models.IntegerField(default=60)),
                ('order_in_workout', models.IntegerField(default=0)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.workout')),
            ],
            options={
                'ordering': ['order_in_workout'],
            },
        ),
        migrations.AddField(
            model_name='workout',
            name='exercises',
            field=models.ManyToManyField(related_name='workouts', through='core.WorkoutExercise', to='core.exercise'),
        ),
        migrations.AddField(
            model_name='workout',
            name='suitable_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.workoutexperience'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('height_cm', models.IntegerField(blank=True, null=True)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('physical_limitations', models.TextField(blank=True, null=True)),
                ('fitness_goals', models.ManyToManyField(blank=True, to='core.fitnessgoal')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('fitness_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.workoutexperience')),
            ],
        ),
        migrations.CreateModel(
            name='FitnessPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('weeks_duration', models.IntegerField(default=4)),
                ('days_per_week', models.IntegerField(default=3)),
                ('schedule', models.TextField(blank=True, null=True)),
                ('dietary_guidelines', models.TextField(blank=True, null=True)),
                ('physical_restrictions', models.TextField(blank=True, null=True)),
                ('workout_preference', models.CharField(default='home', max_length=50)),
                ('goal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fitnessgoal')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workouts', models.ManyToManyField(related_name='fitness_plans', to='core.workout')),
                ('experience_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.workoutexperience')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='difficulty_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.workoutexperience'),
        ),
    ]
